// Code generated by "stringer -trimprefix List -type ListID"; DO NOT EDIT.

package activecampaign

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ListMaster-1]
	_ = x[ListPALocal-3]
	_ = x[ListPAPost-4]
	_ = x[ListInvestigator-5]
	_ = x[ListHowWeCare-6]
	_ = x[ListTalkOfTheTown-7]
	_ = x[ListPennStateAlerts-8]
	_ = x[ListBerksCounty-9]
	_ = x[ListBreakingNews-10]
	_ = x[ListWeekInReview-11]
	_ = x[ListEvents-13]
}

const (
	_ListID_name_0 = "Master"
	_ListID_name_1 = "PALocalPAPostInvestigatorHowWeCareTalkOfTheTownPennStateAlertsBerksCountyBreakingNewsWeekInReview"
	_ListID_name_2 = "Events"
)

var (
	_ListID_index_1 = [...]uint8{0, 7, 13, 25, 34, 47, 62, 73, 85, 97}
)

func (i ListID) String() string {
	switch {
	case i == 1:
		return _ListID_name_0
	case 3 <= i && i <= 11:
		i -= 3
		return _ListID_name_1[_ListID_index_1[i]:_ListID_index_1[i+1]]
	case i == 13:
		return _ListID_name_2
	default:
		return "ListID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
