// Code generated by "stringer -trimprefix Status -type Status"; DO NOT EDIT.

package activecampaign

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnconfirmed-0]
	_ = x[StatusActive-1]
	_ = x[StatusUnsubscribed-2]
	_ = x[StatusBounced-3]
}

const _Status_name = "UnconfirmedActiveUnsubscribedBounced"

var _Status_index = [...]uint8{0, 11, 17, 29, 36}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
